<a href="https://colab.research.google.com/github/josephenik2-design/Applied-AI-Sequence-Models/blob/main/AI_Risk_Lab_Dataset_Audit_Starter_EN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
from google.colab import files
uploaded = files.upload()

Saving Variant_D_Fraud_Detection.csv to Variant_D_Fraud_Detection.csv

In [17]:
import pandas as pd
import numpy as np

DATA_FILE = "Variant_D_Fraud_Detection.csv"
TARGET_COLUMN = "fraud_label"

df = pd.read_csv(DATA_FILE)
print("Rows and columns:", df.shape)
display(df.head(10))

audit = pd.DataFrame({
    "dtype": df.dtypes.astype(str),
    "missing_count": df.isna().sum(),
    "missing_pct": (df.isna().mean() * 100).round(2),
    "unique_values": df.nunique(dropna=True)
})
display(audit)
print("Exact duplicate rows:", int(df.duplicated().sum()))

display(df.describe(include="number").T)
for col in df.select_dtypes(include=["object", "category", "string"]).columns:
    print(f"\n--- {col} ---")
    display(df[col].value_counts(dropna=False).head(25))

display(df[TARGET_COLUMN].value_counts(dropna=False).to_frame("count"))

# extra evidence for the report
d = df.drop_duplicates()
print(pd.crosstab(d["fraud_label"].fillna(-1), d["chargeback_confirmed_after_30d"]))
for col in ["country_risk_band", "channel", "merchant_category", "event_month"]:
    print(f"\n{col}")
    print(d.groupby(col)[["fraud_label", "chargeback_confirmed_after_30d"]].agg(["sum", "count"]))

Rows and columns: (162, 10)

,transaction_id,amount,hour_utc,channel,merchant_category,device_changed_recently,country_risk_band,fraud_label,chargeback_confirmed_after_30d,event_month
0,T00001,65.86,16,Web,Food,0.0,High,0.0,0,2025-03
1,T00002,264.59,10,Mobile,Digital goods,0.0,Low,0.0,0,2025-02
2,T00003,13.01,18,Mobile,Food,0.0,Medium,0.0,0,2025-02
3,T00004,24.37,19,Mobile,Food,0.0,Low,0.0,0,2025-02
4,T00005,38.94,3,Web,Retail,1.0,Medium,0.0,0,2025-02
5,T00006,93.79,14,mobile,Food,0.0,Low,0.0,0,2025-01
6,T00007,37.85,8,Web,Transfer,0.0,High,0.0,0,2025-01
7,T00008,NaN,10,Web,Digital goods,0.0,Low,0.0,0,2025-01
8,T00009,63.02,3,Mobile,Retail,0.0,Low,0.0,0,2025-01
9,T00010,122.37,1,Mobile,Digital goods,0.0,Low,0.0,0,2025-04

,dtype,missing_count,missing_pct,unique_values
transaction_id,object,0,0.00,160
amount,float64,3,1.85,157
hour_utc,int64,0,0.00,25
channel,object,2,1.23,4
merchant_category,object,0,0.00,6
device_changed_recently,float64,2,1.23,3
country_risk_band,object,0,0.00,4
fraud_label,float64,1,0.62,2
chargeback_confirmed_after_30d,int64,0,0.00,2
event_month,object,0,0.00,4

Exact duplicate rows: 2

,count,mean,std,min,25%,50%,75%,max
amount,159.0,52.152453,58.180991,-12.9,14.95,35.89,68.405,352.32
hour_utc,162.0,11.938272,6.951198,0.0,6.00,12.00,18.000,27.00
device_changed_recently,160.0,0.100000,0.358193,0.0,0.00,0.00,0.000,3.00
fraud_label,161.0,0.024845,0.156137,0.0,0.00,0.00,0.000,1.00
chargeback_confirmed_after_30d,162.0,0.043210,0.203960,0.0,0.00,0.00,0.000,1.00

--- transaction_id ---

transaction_id
T00032    2
T00100    2
T00003    1
T00001    1
T00005    1
T00006    1
T00007    1
T00002    1
T00009    1
T00010    1
T00011    1
T00012    1
T00013    1
T00014    1
T00015    1
T00004    1
T00016    1
T00017    1
T00019    1
T00018    1
T00021    1
T00022    1
T00023    1
T00020    1
T00024    1
Name: count, dtype: int64

--- channel ---

channel
Mobile    85
Web       57
POS       17
NaN        2
mobile     1
Name: count, dtype: int64

--- merchant_category ---

merchant_category
Food             44
Retail           41
Digital goods    34
Transfer         31
Travel           11
Digital Goods     1
Name: count, dtype: int64

--- country_risk_band ---

country_risk_band
Low       110
Medium     39
High       12
high        1
Name: count, dtype: int64

--- event_month ---

event_month
2025-01    64
2025-02    42
2025-03    34
2025-04    22
Name: count, dtype: int64

             count
fraud_label
0.0            157
1.0              4
NaN              1

chargeback_confirmed_after_30d    0  1
fraud_label
-1.0                              1  0
 0.0                            151  4
 1.0                              1  3

country_risk_band
                  fraud_label       chargeback_confirmed_after_30d
                          sum count                            sum count
country_risk_band
High                      0.0    12                              0    12
Low                       4.0   108                              7   109
Medium                    0.0    38                              0    38
high                      0.0     1                              0     1

channel
        fraud_label       chargeback_confirmed_after_30d
                sum count                            sum count
channel
Mobile          2.0    83                              3    84
POS             0.0    17                              0    17
Web             2.0    56                              4    56
mobile          0.0     1                              0     1

merchant_category
                  fraud_label       chargeback_confirmed_after_30d
                          sum count                            sum count
merchant_category
Digital Goods             0.0     1                              0     1
Digital goods             1.0    33                              1    33
Food                      1.0    44                              2    44
Retail                    2.0    41                              3    41
Transfer                  0.0    30                              1    31
Travel                    0.0    10                              0    10

event_month
            fraud_label       chargeback_confirmed_after_30d
                    sum count                            sum count
event_month
2025-01             2.0    63                              3    63
2025-02             1.0    41                              3    41
2025-03             1.0    34                              0    34
2025-04             0.0    21                              1    22

In [18]:
print(d.groupby(col)[["fraud_label", "chargeback_confirmed_after_30d"]]
      .agg(["sum", "count"]))

            fraud_label       chargeback_confirmed_after_30d
                    sum count                            sum count
event_month
2025-01             2.0    63                              3    63
2025-02             1.0    41                              3    41
2025-03             1.0    34                              0    34
2025-04             0.0    21                              1    22

In [20]:
pd.set_option("display.width", 100)
pd.set_option("display.max_columns", 20)